spring:
  datasource:
    url: jdbc:mariadb://haconaka.com:3306/ds6951
    username: ds6951
    password: soldesk802!!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.haconaka.demo: INFO
    org.hibernate.SQL: WARN

youtube:
  callback-base-url: "https://neologically-caulocarpous-elenora.ngrok-free.dev"
  api-key: "AIzaSyDaJwlJQy--MSHz_DRBAcvTi2tc4Cg78CY"