spring:
  datasource:
#    url: jdbc:postgresql://dpg-d5qj2kcoud1c73e7m2q0-a.oregon-postgres.render.com/haconaka
    url: jdbc:postgresql://dpg-d5qj2kcoud1c73e7m2q0-a/haconaka
    username: ds6951
    password: 5NTAVOTYcLGwX4vsbByXkpsQPIraYEzv
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


server:
  port: 8080

logging:
  level:
    com.haconaka.demo: INFO
    org.hibernate.SQL: WARN

youtube:
#  callback-base-url: "https://neologically-caulocarpous-elenora.ngrok-free.dev"
  callback-base-url: "https://haconaka-backend-java.onrender.com"
  api-key: "AIzaSyDaJwlJQy--MSHz_DRBAcvTi2tc4Cg78CY"